UPDATE `role` SET name = 'LEARNING_MANAGER' WHERE name = 'COURSE_MANAGER';

INSERT INTO `role` (name) VALUES
('LEARNING_CREATE'),
('LEARNING_PUBLISH'),
('LEARNING_EDIT'),
('LEARNING_ARCHIVE'),
('LEARNING_DELETE'),
('CSL_AUTHOR'),
('ORGANISATION_AUTHOR'),
('PROFESSION_AUTHOR'),
('SUPPLIER_AUTHOR')
;
